language: php

php:
  - 5.5
  - 5.6

before-script:
  #install stuff with composer
  composer --working-dir=./vendors install

script:
  ./vendors/vendor/bin/phpunit --bootstrap ./engine/tests/bootstrap.php ./engine/tests/