language: php

php:
  - 5.6

services:
  - mongodb

before-script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  #install stuff with composer
  - composer --working-dir=./vendors install
  #- pecl install mongo

script:
  - vendors/vendor/bin/phpunit --bootstrap engine/tests/bootstrap.php engine/tests/