language: php

php:
  - 5.6

install:
  #install stuff with composer
  composer --working-dir=./vendors install
  pecl install mongo

services:
  - mongodb

script:
  vendors/vendor/bin/phpunit --bootstrap engine/tests/bootstrap.php engine/tests/