language: php

php:
  - 5.6

before-script:
  #install stuff with composer
  composer --working-dir=./vendors install

script:
  #pwd
  #ls
  #tree .
  vendors/vendor/bin/phpunit --bootstrap engine/tests/bootstrap.php engine/tests/