language: php

php:
  - 5.6

services:
  - mongodb

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

script:
  - vendor/bin/phpunit --bootstrap engine/tests/bootstrap.php engine/tests/